# Generated by Django 4.1.7 on 2023-03-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon_explanation', models.CharField(blank=True, max_length=200, null=True)),
                ('incon_second_explanation', models.CharField(blank=True, max_length=200, null=True)),
                ('incon2', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon_explanation2', models.CharField(blank=True, max_length=200, null=True)),
                ('incon_second_explanation2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts_Plus_Social_Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook', models.ImageField(blank=True, null=True, upload_to='socialMedia/')),
                ('twitter', models.ImageField(blank=True, null=True, upload_to='socialMedia/')),
                ('instagram', models.ImageField(blank=True, null=True, upload_to='socialMedia/')),
                ('youtube', models.ImageField(blank=True, null=True, upload_to='socialMedia/')),
                ('linkedin', models.ImageField(blank=True, null=True, upload_to='socialMedia/')),
            ],
        ),
        migrations.CreateModel(
            name='FreeQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='OurProjects/')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_ongoing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('incon', models.ImageField(blank=True, null=True, upload_to='Services/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='sliderIMages/')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='TeamMembers/Profiles/')),
                ('twitter_icone', models.ImageField(blank=True, null=True, upload_to='TeamMembers/SocialMediaIcons/')),
                ('instagram_icon', models.ImageField(blank=True, null=True, upload_to='TeamMembers/SocialMediaIcons/')),
                ('linkedin_icon', models.ImageField(blank=True, null=True, upload_to='TeamMembers/SocialMediaIcons/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Testimonials/')),
                ('image_icon', models.ImageField(blank=True, null=True, upload_to='Testimonials/')),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('incon', models.ImageField(blank=True, null=True, upload_to='WhyChooseUs/')),
                ('incon_title', models.CharField(blank=True, max_length=200, null=True)),
                ('incon_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
