# Generated by Django 4.1.7 on 2023-03-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('incon', models.ImageField(blank=True, null=True, upload_to='SummaryServices/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='SummaryServices/')),
            ],
        ),
    ]
