# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_summaryservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='facebook_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='instagram_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='linkedin_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='twitter_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='youtube_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
