# Generated by Django 4.1.7 on 2023-03-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contacts_plus_social_media_open_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='incon_description',
        ),
        migrations.RemoveField(
            model_name='whychooseus',
            name='incon_title',
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.whychooseussummary'),
        ),
    ]
