# Generated by Django 4.1.7 on 2023-03-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_whychooseussummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseussummary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='WhyChooseUs/'),
        ),
    ]
