# Generated by Django 4.1.7 on 2023-03-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_whychooseussummary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojects',
            name='is_completed',
            field=models.CharField(blank=True, choices=[('first', 'completed'), ('second', 'on going')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ourprojects',
            name='is_ongoing',
            field=models.CharField(blank=True, choices=[('first', 'completed'), ('second', 'on going')], max_length=200, null=True),
        ),
    ]
