# Generated by Django 4.1.7 on 2023-03-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ourprojects_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourprojects',
            name='summary',
        ),
    ]
