# Generated by Django 4.1.7 on 2023-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_ourprojects_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourprojects',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='is_ongoing',
        ),
        migrations.AddField(
            model_name='ourprojects',
            name='status',
            field=models.CharField(blank=True, choices=[('first', 'completed'), ('second', 'on going'), ('third', False)], max_length=200, null=True),
        ),
    ]
