# Generated by Django 4.1.7 on 2023-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ourprojects_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourprojects',
            name='status',
            field=models.CharField(blank=True, choices=[('first', 'completed'), ('second', 'on going')], default=True, max_length=200, null=True),
        ),
    ]
