# Generated by Django 4.1.7 on 2023-03-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ourprojects_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeQuote',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='twitter_icone',
            new_name='twitter_icon',
        ),
    ]
