# Generated by Django 4.1.7 on 2023-03-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_teammembers_instagram_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='testimonials',
            old_name='title',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='image_icon',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='summary',
        ),
    ]
