# Generated by Django 4.1.7 on 2023-03-29 17:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_name_testimonials_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
