# Generated by Django 4.1.7 on 2023-03-30 12:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_linkedin_link_teammembers_facebook_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts_plus_social_media',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contacts_plus_social_media',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contacts_plus_social_media',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contacts_plus_social_media',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contacts_plus_social_media',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
