# Generated by Django 4.1.7 on 2023-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactus_remove_contacts_plus_social_media_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
