# Generated by Django 4.1.7 on 2023-03-30 15:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_contactus_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='opening_message',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
