# Generated by Django 4.1.7 on 2023-03-30 15:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contactus_opening_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='opening_message',
        ),
        migrations.AddField(
            model_name='contacts_plus_social_media',
            name='opening_message',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
