# Generated by Django 4.1.7 on 2023-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_contactus_opening_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_plus_social_media',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contacts_plus_social_media',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contacts_plus_social_media',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contacts_plus_social_media',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='contacts_plus_social_media',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
