# Generated by Django 4.1.7 on 2023-03-30 16:28

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_contacts_plus_social_media_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopHomePageLabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon_explanation', models.CharField(blank=True, max_length=200, null=True)),
                ('incon_second_explanation', models.CharField(blank=True, max_length=200, null=True)),
                ('incon2', models.ImageField(blank=True, null=True, upload_to='AboutUsImages/')),
                ('incon_explanation2', models.CharField(blank=True, max_length=200, null=True)),
                ('incon_second_explanation2', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
