# Generated by Django 4.1.7 on 2023-03-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_shophomepagelabels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon',
        ),
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon2',
        ),
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon_explanation',
        ),
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon_explanation2',
        ),
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon_second_explanation',
        ),
        migrations.RemoveField(
            model_name='shophomepagelabels',
            name='incon_second_explanation2',
        ),
    ]
