# Generated by Django 4.1.7 on 2023-04-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_shophomepagelabels_incon_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetter',
        ),
        migrations.DeleteModel(
            name='ShopHomePageLabels',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us Information', 'verbose_name_plural': 'About Us Information'},
        ),
        migrations.AlterModelOptions(
            name='contacts_plus_social_media',
            options={'verbose_name': 'Contact Information plus social media details', 'verbose_name_plural': 'Contact Information plus social media details'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Messages From Potential Clients', 'verbose_name_plural': 'Messages From Potential Clients'},
        ),
        migrations.AlterModelOptions(
            name='ourprojects',
            options={'verbose_name': 'Projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Services [max 6]', 'verbose_name_plural': 'Services [max 6]'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider Images and descriptions', 'verbose_name_plural': 'Slider Images and descriptions'},
        ),
        migrations.AlterModelOptions(
            name='summaryservices',
            options={'verbose_name': 'Brief Snippets Of services Offered [put only 3 items]', 'verbose_name_plural': 'Brief Snippets Of services Offered [put only 3 items]'},
        ),
        migrations.AlterModelOptions(
            name='teammembers',
            options={'verbose_name': 'Team Members', 'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name': 'Why Choose Us', 'verbose_name_plural': 'Why Choose Us'},
        ),
        migrations.AlterModelOptions(
            name='whychooseussummary',
            options={'verbose_name': 'Why Choose Us Brief Information', 'verbose_name_plural': 'Why Choose Us Brief Information'},
        ),
    ]
