# Generated by Django 4.1.7 on 2023-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_aboutus_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackGroundImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='section where this backgound image is going to be displayed', max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='BackGroundImages/')),
            ],
        ),
    ]
