# Generated by Django 4.1.7 on 2023-04-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sectors_alter_whychooseus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectors',
            name='description',
        ),
    ]
