# Generated by Django 4.1.7 on 2023-04-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_sectors_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhyChooseUs',
            new_name='Feature',
        ),
        migrations.RenameModel(
            old_name='WhyChooseUsSummary',
            new_name='FeatureSummary',
        ),
    ]
