# Generated by Django 4.1.7 on 2023-04-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_whychooseus_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='featureName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='FeatureSummary',
        ),
    ]
