# Generated by Django 4.1.7 on 2023-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_feature_featurename_alter_feature_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Feature'},
        ),
        migrations.RemoveField(
            model_name='feature',
            name='incon',
        ),
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Feature/'),
        ),
    ]
