# Generated by Django 4.1.7 on 2023-04-03 18:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_feature_options_remove_feature_incon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBeliefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belief', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='OurBeliefs/')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='OurBeliefs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon_explanation',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon_explanation2',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon_second_explanation',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='incon_second_explanation2',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='secttion1',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='secttion2',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='secttion3',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_beliefs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ourbeliefs'),
        ),
    ]
