# Generated by Django 4.1.7 on 2023-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_ourbeliefs_remove_aboutus_incon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbeliefs',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
