# Generated by Django 4.1.7 on 2023-04-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_ourbeliefs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='summary2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
