# Generated by Django 4.1.7 on 2023-04-03 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_image_aboutus_image2_aboutus_image_homepage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='image_main',
            new_name='image',
        ),
    ]
