# Generated by Django 4.1.7 on 2023-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_aboutus_background_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='background_image2',
            field=models.ImageField(blank=True, null=True, upload_to='AboutUsImages/'),
        ),
    ]
