# Generated by Django 4.1.7 on 2023-04-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_aboutus_background_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='background_image1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='background_image2',
        ),
    ]
