# Generated by Django 4.1.7 on 2023-04-03 21:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_aboutus_background_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image_secttion1',
            field=models.ImageField(blank=True, null=True, upload_to='AboutUsImages/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='image_secttion2',
            field=models.ImageField(blank=True, null=True, upload_to='AboutUsImages/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='secttion4',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
