# Generated by Django 4.1.7 on 2023-04-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_image_secttion2_aboutus_image_our_beliefs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='our_beliefs',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_beliefs',
            field=models.ManyToManyField(blank=True, to='main.ourbeliefs'),
        ),
    ]
