# Generated by Django 4.1.7 on 2023-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_remove_aboutus_our_beliefs_aboutus_our_beliefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
